version: '3'
services:
  web:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_started
    environment:
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recon_tool

volumes:
  pgdata:
